# .github/FUNDING.yml
github: [blixten85]
custom: ["https://www.paypal.com/donate?business=anders.eriksson@denied.se&currency_code=SEK&item_name=Politiker-kontakt"]
custom: ["https://whydonate.com/sv/donate/politiker-kontakt"]
